################################################################################
## Script:  trophic_amp_figures_pt2.R
## Project: NES-LTER Trophic Amplification 
##          Cross-Site LTER Pelagic Synthesis Working Group
## Author:  Alexandra C. Cabanelas Bermudez
## Created: March 2026
##
## Purpose: Compares larval fish anomalies with corresponding forage fish
##          taxa (Atlantic herring, Atlantic mackerel, butterfish, sand lance)
##
## Inputs :
##   - ff_species_level_1963_2025.csv (data/output/)
##   - EcoMon_plankton_v3_10.csv  (data/raw/)
##       ichthyoplankton abundance per 10m2
################################################################################

## ------------------------------------------ ##
#            Packages
## ------------------------------------------ ##
library(tidyverse)
library(janitor)
library(patchwork)

## ------------------------------------------ ##
#            Load Raw Data
## ------------------------------------------ ##

## --- Forage fish (species-level) ---
## Generated by trophic_amp_foragefish.R at the ff object stage,
## after corrections + region assignment + calendar season,
ff_species <- read_csv(here::here("data", "output",
                                  "ff_species_level_1963_2025.csv")) %>%
  filter(between(year, 1998, 2023))

## quick checks
ff_species %>% count(target_taxa)
ff_species %>% count(target_taxa, season, region) %>% print(n = 40)

## --- Larval fish (EcoMon raw) ---
ichthyo_full <- read_csv(here::here("data", "raw",
                                    "EcoMon_plankton_v3_10.csv")) %>%
  clean_names()

## ------------------------------------------ ##
#            Tidy Larval Fish
## ------------------------------------------ ##
## Species columns (abundance per 10m²):
##   cluhar_10m2 = Atlantic herring  (Clupea harengus)
##   scosco_10m2 = Atlantic mackerel (Scomber scombrus)
##   pepspp_10m2 = Butterfish        (Peprilus spp.)
##   ammspp_10m2 = Sand lance        (Ammodytes spp.)

ichthyo <- ichthyo_full %>%
  ## regions of interest; SNE -> MAB to align with forage fish
  filter(region %in% c("SNE", "MAB", "GOM", "GB")) %>%
  mutate(region = case_when(
    region == "SNE" ~ "MAB",
    TRUE            ~ region
  )) %>%
  select(
    cruise_name, station, zoo_gear, ich_gear,
    date, day, month, month_num, year, time,
    depth, season, region, lon, lat,
    sfc_temp, sfc_salt, btm_temp, btm_salt,
    cluhar_10m2,
    scosco_10m2,
    pepspp_10m2,
    ammspp_10m2
  ) %>%
  ## drop rows with no ichthyo sampling
  filter(!is.na(ich_gear)) %>%
  ## resolve known duplicates (HB2303/sta14, PC2104/sta122, PC2106/sta88)
  ## fish values identical across duplicates; zoo values differ — take first
  arrange(cruise_name, station, region, date,
          desc(zoo_gear == "6B3Z")) %>%
  distinct(cruise_name, station, region, date, .keep_all = TRUE)

rm(ichthyo_full)

## --- Pivot to long (one row per station × taxa) ---
larval_long <- ichthyo %>%
  pivot_longer(
    cols      = c(cluhar_10m2, scosco_10m2, pepspp_10m2, ammspp_10m2),
    names_to  = "spp_col",
    values_to = "cpue_10m2"
  ) %>%
  mutate(
    target_taxa = case_when(
      spp_col == "cluhar_10m2" ~ "Atlantic herring",
      spp_col == "scosco_10m2" ~ "Atlantic mackerel",
      spp_col == "pepspp_10m2" ~ "Butterfish",
      spp_col == "ammspp_10m2" ~ "Sand lance"
    )
  ) %>%
  select(-spp_col) %>%
  filter(between(year, 1998, 2023))

## quick checks
larval_long %>% count(target_taxa)
larval_long %>% count(target_taxa, season, region) %>% print(n = 40)

## --- Confirm season labels match between datasets ---
cat("Forage fish seasons: ", paste(sort(unique(ff_species$season)),  collapse = ", "), "\n")
cat("Larval fish seasons: ", paste(sort(unique(larval_long$season)), collapse = ", "), "\n")

## ------------------------------------------ ##
#            Compute Z-score Anomalies
## ------------------------------------------ ##

## --- Forage fish ---
ff_anom <- ff_species %>%
  group_by(target_taxa, year, season, region) %>%
  summarise(wtcpue = mean(wtcpue, na.rm = TRUE), .groups = "drop") %>%
  group_by(target_taxa, season, region) %>%
  mutate(
    log_cpue       = log1p(wtcpue),
    anomaly_zscore = (wtcpue   - mean(wtcpue,   na.rm = TRUE)) / sd(wtcpue,   na.rm = TRUE),
    anomaly_log    = (log_cpue - mean(log_cpue, na.rm = TRUE)) / sd(log_cpue, na.rm = TRUE)
  ) %>%
  ungroup() %>%
  mutate(source = "Forage fish (adult)\nkg tow⁻¹")

## --- Larval fish ---
larval_anom <- larval_long %>%
  group_by(target_taxa, year, season, region) %>%
  summarise(cpue = mean(cpue_10m2, na.rm = TRUE), .groups = "drop") %>%
  group_by(target_taxa, season, region) %>%
  mutate(
    log_cpue       = log1p(cpue),
    anomaly_zscore = (cpue     - mean(cpue,     na.rm = TRUE)) / sd(cpue,     na.rm = TRUE),
    anomaly_log    = (log_cpue - mean(log_cpue, na.rm = TRUE)) / sd(log_cpue, na.rm = TRUE)
  ) %>%
  ungroup() %>%
  ## rename to common column name for easy bind
  rename(wtcpue = cpue) %>%
  mutate(source = "Larval fish\nno. 10m⁻²")

## --- Combined (for Fig 10) ---
combined_anom <- bind_rows(ff_anom, larval_anom)

## taxa loop vector
taxa_pairs <- c("Atlantic herring", "Atlantic mackerel", "Butterfish", "Sand lance")

## ------------------------------------------ ##
#            Plot Helper
## ------------------------------------------ ##
## Shared ribbon anomaly plot function
## anomaly_col: which column to plot on y ("anomaly_zscore" or "anomaly_log")

anomaly_ribbon_plot <- function(df, taxa_name, src_label,
                                anomaly_col = "anomaly_zscore") {
  df %>%
    filter(target_taxa == taxa_name, source == src_label) %>%
    ggplot(aes(x = year, y = .data[[anomaly_col]])) +
    geom_hline(yintercept = 0, linetype = "dashed", color = "gray50") +
    geom_ribbon(aes(ymin = pmin(.data[[anomaly_col]], 0), ymax = 0),
                fill = "steelblue", alpha = 0.4) +
    geom_ribbon(aes(ymin = 0, ymax = pmax(.data[[anomaly_col]], 0)),
                fill = "tomato",    alpha = 0.4) +
    geom_line(color = "gray30", linewidth = 0.5) +
    facet_grid(season ~ region) +
    labs(
      x = NULL,
      y = if (anomaly_col == "anomaly_zscore") "z-score anomaly (raw WTCPUE)"
      else "z-score anomaly (log-transformed WTCPUE)"
    ) +
    theme_minimal() +
    theme(
      axis.text.x = element_text(angle = 45, hjust = 1),
      strip.text  = element_text(face = "bold")
    )
}

## ------------------------------------------ ##
#  FIGURE 11: Forage Fish Anomaly by Species
## ------------------------------------------ ##

for (sp in taxa_pairs) {
  
  p <- anomaly_ribbon_plot(ff_anom, sp, 
                           src_label   = unique(ff_anom$source),
                           anomaly_col = "anomaly_zscore") +
    anomaly_ribbon_plot(ff_anom, sp, 
                        src_label   = unique(ff_anom$source),
                        anomaly_col = "anomaly_log") +
    plot_annotation(
      title = paste0(sp, " — Forage fish (kg tow\u207b\u00b9)"),
      theme = theme(plot.title = element_text(face = "bold", size = 14))
    )
  
  print(p)
  
  # ggsave(
  #   filename = here::here("figures",
  #                         paste0("fig11_ff_anomaly_", gsub(" ", "_", sp), ".png")),
  #   plot  = p,
  #   width = 14, height = 7, dpi = 300
  # )
}

## ------------------------------------------ ##
#  FIGURE 12: Sand Lance Comparison
##     A. dubius (181) vs A. americanus (734)
## ------------------------------------------ ##

sandlance_raw <- ff_species %>%
  filter(svspp %in% c("181", "734")) %>%
  mutate(species_name = case_when(
    svspp == "181" ~ "N. sand lance (A. dubius)",
    svspp == "734" ~ "Am. sand lance (A. americanus)"
  )) %>%
  group_by(species_name, year, season, region) %>%
  summarise(wtcpue = mean(wtcpue, na.rm = TRUE), .groups = "drop")

## 12a: Raw annual mean WTCPUE
fig12 <- ggplot(sandlance_raw, aes(x = year, y = wtcpue,
                                    color = species_name)) +
  geom_point(size = 1.8, alpha = 0.8) +
  geom_line(linewidth = 0.5, alpha = 0.8) +
  facet_grid(season ~ region, scales = "free_y") +
  scale_color_manual(
    values = c("N. sand lance (A. dubius)"       = "steelblue",
               "Am. sand lance (A. americanus)"  = "tomato"),
    name = NULL
  ) +
  labs(
    title    = "Sand lance — raw annual mean WTCPUE",
    subtitle = "1998–2023",
    x = NULL, y = "WTCPUE (kg tow⁻¹)"
  ) +
  theme_minimal() +
  theme(
    axis.text.x  = element_text(angle = 45, hjust = 1),
    strip.text   = element_text(face = "bold"),
    legend.position = "bottom"
  )

print(fig12)

## ------------------------------------------ ##
#  FIGURE 13: Larval Fish Anomaly by Taxa
##   z-score and log side-by-side, all taxa
## ------------------------------------------ ##

for (sp in taxa_pairs) {
  
  p <- anomaly_ribbon_plot(larval_anom, sp,
                           src_label   = unique(larval_anom$source),
                           anomaly_col = "anomaly_zscore") +
    anomaly_ribbon_plot(larval_anom, sp,
                        src_label   = unique(larval_anom$source),
                        anomaly_col = "anomaly_log") +
    plot_annotation(
      title = paste(sp),
      theme = theme(plot.title = element_text(face = "bold", size = 14))
    )
  
  print(p)
  
  # ggsave(
  #   filename = here::here("figures",
  #                         paste0("fig13_larval_anomaly_", gsub(" ", "_", sp), ".png")),
  #   plot  = p,
  #   width = 14, height = 7, dpi = 300
  # )
}

## ------------------------------------------ ##
#  FIGURE 14: Paired Larval vs. FF Anomaly
##    Left = larval fish | Right = forage fish 
## ------------------------------------------ ##
## units: larval = no. 10m-2; forage fish = kg tow-1
## Both z-score standardized — panels comparable as anomalies

for (sp in taxa_pairs) {
  
  p_larval <- anomaly_ribbon_plot(combined_anom, sp,
                                  src_label   = unique(larval_anom$source),
                                  anomaly_col = "anomaly_zscore")
  
  p_ff     <- anomaly_ribbon_plot(combined_anom, sp,
                                  src_label   = unique(ff_anom$source),
                                  anomaly_col = "anomaly_zscore")
  
  paired <- p_larval + p_ff +
    plot_layout(axes = "collect") +
    plot_annotation(
      title    = paste(sp),
      caption  = "Left: larval fish (no. 10m⁻²) | Right: adult forage fish (kg tow⁻¹) | Both z-score standardized",
      theme    = theme(
        plot.title   = element_text(face = "bold", size = 14),
        plot.caption = element_text(size = 9, color = "gray40")
      )
    )
  
  print(paired)
  
  # ggsave(
  #   filename = here::here("figures",
  #                         paste0("fig14a_larval_vs_ff_", gsub(" ", "_", sp), ".png")),
  #   plot  = paired,
  #   width = 14, height = 7, dpi = 300
  # )
}

## ------------------------------------------ ##
#  FIGURE 14b: Fall and Spring

ff_anom1 <- ff_anom %>% 
  filter(season %in% c("Spring", "Fall"))

larval_anom1 <- larval_anom %>% 
  filter(season %in% c("Spring", "Fall"))

combined_anom1 <- bind_rows(ff_anom1, larval_anom1)

for (sp in taxa_pairs) {
  
  p_larval1 <- anomaly_ribbon_plot(combined_anom1, sp,
                                  src_label   = unique(larval_anom1$source),
                                  anomaly_col = "anomaly_zscore")
  
  p_ff1     <- anomaly_ribbon_plot(combined_anom1, sp,
                                  src_label   = unique(ff_anom1$source),
                                  anomaly_col = "anomaly_zscore")
  
  paired1 <- p_larval1 + p_ff1 +
    plot_layout(axes = "collect") +
    plot_annotation(
      title   = paste0(sp, " — larval fish vs. forage fish"),
      caption = "Left: larval fish (no. 10m\u207b\u00b2) | Right: forage fish (kg tow\u207b\u00b9) | Both z-score standardized",
      theme   = theme(
        plot.title   = element_text(face = "bold", size = 14),
        plot.caption = element_text(size = 9, color = "gray40")
      )
    )
  
  print(paired1)
  
  # ggsave(
  #   filename = here::here("figures",
  #                         paste0("fig14b_larval_vs_ff_", gsub(" ", "_", sp), ".png")),
  #   plot  = paired,
  #   width = 14, height = 7, dpi = 300
  # )
}
